name: streamlit-causalimpact
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12.4
  - pip:
    - tfp-causalimpact==0.2.0
    - matplotlib==3.8.4
    - numpy==1.26.4
    - pandas==2.2.2
    - scikit_learn==1.4.2
    - scipy==1.13.1
    - streamlit==1.41.1
    - tensorflow==2.17.0
    - tensorflow_intel==2.17.0
    - tf_keras==2.17.0
    - tensorflow_probability==0.24.0